version: "3"

vars:
  GIT_CLIFF: '{{.APPDATA}}\Python\Python313\Scripts\git-cliff.exe'
  GODOT: 'C:\lunar-horse\tools\Godot_v4.6.1-stable_mono_win64\Godot_v4.6.1-stable_mono_win64_console.exe'
  SLN: project/GiantIsopod.sln
  GODOT_PROJECT: project/hosts/complete-app
  SKILLS_CONFIG: .agent/skills.json
  SKILLS_DIR: .agent/skills
  SKILLS_TEMP: .agent/.skills-temp

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  version:
    desc: Show the current version from GitVersion
    cmds:
      - dotnet-gitversion /showvariable SemVer

  changelog:
    desc: Generate CHANGELOG.md using version from GitVersion
    vars:
      VERSION:
        sh: dotnet-gitversion /showvariable SemVer
    cmds:
      - '"{{.GIT_CLIFF}}" --tag v{{.VERSION}} -o CHANGELOG.md'

  changelog:preview:
    desc: Preview changelog without writing to file
    vars:
      VERSION:
        sh: dotnet-gitversion /showvariable SemVer
    cmds:
      - '"{{.GIT_CLIFF}}" --tag v{{.VERSION}}'

  changelog:unreleased:
    desc: Show only unreleased changes
    cmds:
      - '"{{.GIT_CLIFF}}" --unreleased'

  lint:
    desc: Run ruff linter
    cmds:
      - ruff check --config ruff/ruff.toml .

  lint:fix:
    desc: Run ruff linter with auto-fix
    cmds:
      - ruff check --config ruff/ruff.toml --fix .

  format:
    desc: Run ruff formatter
    cmds:
      - ruff format --config ruff/ruff.toml .

  pre-commit:
    desc: Run all pre-commit hooks on all files
    cmds:
      - pre-commit run --all-files

  pre-commit:install:
    desc: Install pre-commit hooks
    cmds:
      - pre-commit install

  secrets:scan:
    desc: Scan for secrets and update baseline
    cmds:
      - detect-secrets scan --baseline .secrets.baseline

  release:
    desc: Tag and release using GitVersion's calculated version
    vars:
      VERSION:
        sh: dotnet-gitversion /showvariable SemVer
    cmds:
      - git tag v{{.VERSION}}
      - '"{{.GIT_CLIFF}}" --tag v{{.VERSION}} -o CHANGELOG.md'
      - git add CHANGELOG.md
      - 'git commit -m "chore(release): v{{.VERSION}}"'

  skills:install:
    desc: Install all external skills from .agent/skills.json
    cmds:
      - python .agent/skills/install_skills.py
      - cmd: npm install
        dir: .agent/skills/agent-browser

  # ── HUD Generation (boom-hud) ──

  hud:generate:
    desc: Regenerate HUD .tscn scenes from Figma JSON designs via boom-hud
    vars:
      BOOM_HUD_CLI: 'C:\lunar-horse\plate-projects\boom-hud\dotnet\src\BoomHud.Cli\BoomHud.Cli.csproj'
      HUD_DESIGNS: '{{.GODOT_PROJECT}}/HudDesigns'
      HUD_OUTPUT: '{{.GODOT_PROJECT}}/Scenes/Hud'
      HUD_NS: GiantIsopod.Hosts.CompleteApp
    cmds:
      - for:
          - swarm-top-bar
          - agent-list-entry
          - agent-list-panel
          - spawn-controls
          - console-panel
          - swarm-hud
        cmd: >-
          dotnet run --project "{{.BOOM_HUD_CLI}}" -c Release --
          generate "{{.HUD_DESIGNS}}/{{.ITEM}}.figma.json"
          --target godot --tscn --tscn-no-script
          --namespace "{{.HUD_NS}}"
          --output "{{.HUD_OUTPUT}}"

  # ── Memory sidecar ──

  memory:install:
    desc: Install memory-sidecar Python package (editable)
    cmds:
      - uv pip install -e ".[dev]"
    dir: memory-sidecar

  memory:index:
    desc: Index the project codebase into SQLite with vector embeddings
    cmds:
      - memory-sidecar index project/ --db data/memory/codebase.sqlite

  memory:search:
    desc: Search the codebase index (usage — task memory:search -- "your query")
    cmds:
      - memory-sidecar search "{{.CLI_ARGS}}" --db data/memory/codebase.sqlite

  # ── .NET / Godot ──

  build:
    desc: Build the .NET solution (Debug) using UnifyBuild
    cmds:
      - dotnet tool restore
      - dotnet unify-build Compile --configuration Debug

  build:release:
    desc: Build the .NET solution (Release) using UnifyBuild
    cmds:
      - dotnet tool restore
      - dotnet unify-build Compile --configuration Release

  publish:
    desc: Publish the Godot host project and all hosts using UnifyBuild
    cmds:
      - dotnet tool restore
      - dotnet unify-build PublishHosts --configuration Release

  export:
    desc: Export Godot app for all platforms to build/_artifacts/{version}/{rid}
    cmds:
      - powershell -ExecutionPolicy Bypass -File build/export-godot.ps1 -Platforms all

  export:win:
    desc: Export Godot app for Windows only
    cmds:
      - powershell -ExecutionPolicy Bypass -File build/export-godot.ps1 -Platforms win-x64

  export:linux:
    desc: Export Godot app for Linux only
    cmds:
      - powershell -ExecutionPolicy Bypass -File build/export-godot.ps1 -Platforms linux-x64

  export:mac:
    desc: Export Godot app for macOS only
    cmds:
      - powershell -ExecutionPolicy Bypass -File build/export-godot.ps1 -Platforms osx-universal

  export:clean:
    desc: Clean build artifacts and re-export all platforms
    cmds:
      - cmd: powershell -NoProfile -Command "Remove-Item -Recurse -Force build/_artifacts -ErrorAction SilentlyContinue"
      - task: export

  godot:editor:
    desc: Open the Godot editor for the complete-app project
    cmds:
      - cmd: '"{{.GODOT}}" --path {{.GODOT_PROJECT}} --editor'

  clean:
    desc: Clean all build outputs
    cmds:
      - dotnet clean {{.SLN}} --nologo -v quiet
      - cmd: powershell -NoProfile -Command "Remove-Item -Recurse -Force build/_artifacts -ErrorAction SilentlyContinue"
