// <auto-generated>
// Generated by BoomHud.Gen.Godot from Agentlistpanel
// </auto-generated>

#nullable enable

using Godot;
using System;
using System.ComponentModel;

namespace GiantIsopod.Hosts.CompleteApp;

public partial class AgentlistpanelView : VBoxContainer
{
    public const string BoomHudSourceId = "sha256:02574c062c09764c2c9ec892453cd7fe11bce082085760ed61118fb78babc15e";
    public const string BoomHudContractId = "";
    public static readonly string[] BoomHudNormalizedPseudoNodes = new string[0];

    private IAgentlistpanelViewModel? _viewModel;

    // Control references
    private VBoxContainer _agentlistpanel = null!;
    private HBoxContainer _header = null!;
    private Label _headerlabel = null!;
    private VBoxContainer _scrollarea = null!;
    private VBoxContainer _agentlist = null!;

    public override void _Ready()
    {
        base._Ready();
        BindUiFromScene();
        InitializeUiFromScene();
    }

    private void BindUiFromScene()
    {
        _agentlistpanel = this;
        _header = GetNode<HBoxContainer>("header");
        _headerlabel = GetNode<Label>("header/headerlabel");
        _scrollarea = GetNode<VBoxContainer>("scrollarea");
        _agentlist = GetNode<VBoxContainer>("scrollarea/agentlist");
    }

    private void InitializeUiFromScene()
    {
        {
        if ((object)this is Control c)
        {
            c.CustomMinimumSize = new Vector2(240, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 600);
        }
        }
        this.AddThemeConstantOverride("separation", 0);
        this.AddThemeConstantOverride("h_separation", 0);
        this.AddThemeConstantOverride("v_separation", 0);
        this.AddThemeConstantOverride("margin_left", 0);
        this.AddThemeConstantOverride("margin_top", 0);
        this.AddThemeConstantOverride("margin_right", 0);
        this.AddThemeConstantOverride("margin_bottom", 0);

        {
        if ((object)_header is Control c)
        {
            c.CustomMinimumSize = new Vector2(240, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 32);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkBegin;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        _header.AddThemeConstantOverride("separation", 0);
        _header.AddThemeConstantOverride("h_separation", 0);
        _header.AddThemeConstantOverride("v_separation", 0);
        _header.AddThemeConstantOverride("margin_left", 12);
        _header.AddThemeConstantOverride("margin_top", 8);
        _header.AddThemeConstantOverride("margin_right", 12);
        _header.AddThemeConstantOverride("margin_bottom", 8);

        _headerlabel.AddThemeColorOverride("font_color", new Color(0.8f, 0.8f, 0.84705883f, 1f));
        _headerlabel.Set("text", "Agents");

        {
        if ((object)_scrollarea is Control c)
        {
            c.CustomMinimumSize = new Vector2(240, c.CustomMinimumSize.Y);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkBegin;
            c.SizeFlagsVertical = Control.SizeFlags.ExpandFill;
        }
        }
        _scrollarea.AddThemeConstantOverride("separation", 0);
        _scrollarea.AddThemeConstantOverride("h_separation", 0);
        _scrollarea.AddThemeConstantOverride("v_separation", 0);

        {
        if ((object)_agentlist is Control c)
        {
            c.CustomMinimumSize = new Vector2(240, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 568);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkBegin;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        _agentlist.AddThemeConstantOverride("separation", 2);
        _agentlist.AddThemeConstantOverride("h_separation", 2);
        _agentlist.AddThemeConstantOverride("v_separation", 2);
        _agentlist.AddThemeConstantOverride("margin_left", 4);
        _agentlist.AddThemeConstantOverride("margin_top", 4);
        _agentlist.AddThemeConstantOverride("margin_right", 4);
        _agentlist.AddThemeConstantOverride("margin_bottom", 4);
    }

    private void BuildUi()
    {
        {
        if ((object)this is Control c)
        {
            c.CustomMinimumSize = new Vector2(240, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 600);
        }
        }
        this.AddThemeConstantOverride("separation", 0);
        this.AddThemeConstantOverride("h_separation", 0);
        this.AddThemeConstantOverride("v_separation", 0);
        this.AddThemeConstantOverride("margin_left", 0);
        this.AddThemeConstantOverride("margin_top", 0);
        this.AddThemeConstantOverride("margin_right", 0);
        this.AddThemeConstantOverride("margin_bottom", 0);

        _header = new HBoxContainer();
        _header.Name = "header";
        {
        if ((object)_header is Control c)
        {
            c.CustomMinimumSize = new Vector2(240, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 32);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkBegin;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        _header.AddThemeConstantOverride("separation", 0);
        _header.AddThemeConstantOverride("h_separation", 0);
        _header.AddThemeConstantOverride("v_separation", 0);
        _header.AddThemeConstantOverride("margin_left", 12);
        _header.AddThemeConstantOverride("margin_top", 8);
        _header.AddThemeConstantOverride("margin_right", 12);
        _header.AddThemeConstantOverride("margin_bottom", 8);
        this.AddChild(_header);

        _headerlabel = new Label();
        _headerlabel.Name = "headerlabel";
        _headerlabel.AddThemeColorOverride("font_color", new Color(0.8f, 0.8f, 0.84705883f, 1f));
        _headerlabel.Set("text", "Agents");
        _header.AddChild(_headerlabel);

        _scrollarea = new VBoxContainer();
        _scrollarea.Name = "scrollarea";
        {
        if ((object)_scrollarea is Control c)
        {
            c.CustomMinimumSize = new Vector2(240, c.CustomMinimumSize.Y);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkBegin;
            c.SizeFlagsVertical = Control.SizeFlags.ExpandFill;
        }
        }
        _scrollarea.AddThemeConstantOverride("separation", 0);
        _scrollarea.AddThemeConstantOverride("h_separation", 0);
        _scrollarea.AddThemeConstantOverride("v_separation", 0);
        this.AddChild(_scrollarea);

        _agentlist = new VBoxContainer();
        _agentlist.Name = "agentlist";
        {
        if ((object)_agentlist is Control c)
        {
            c.CustomMinimumSize = new Vector2(240, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 568);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkBegin;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        _agentlist.AddThemeConstantOverride("separation", 2);
        _agentlist.AddThemeConstantOverride("h_separation", 2);
        _agentlist.AddThemeConstantOverride("v_separation", 2);
        _agentlist.AddThemeConstantOverride("margin_left", 4);
        _agentlist.AddThemeConstantOverride("margin_top", 4);
        _agentlist.AddThemeConstantOverride("margin_right", 4);
        _agentlist.AddThemeConstantOverride("margin_bottom", 4);
        _scrollarea.AddChild(_agentlist);
    }

    public void SetViewModel(IAgentlistpanelViewModel? viewModel)
    {
        if (_viewModel != null)
        {
            _viewModel.PropertyChanged -= OnViewModelPropertyChanged;
        }

        _viewModel = viewModel;

        if (_viewModel != null)
        {
            _viewModel.PropertyChanged += OnViewModelPropertyChanged;
            UpdateAllBindings();
        }
    }

    private void OnViewModelPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (_viewModel == null) return;

    }

    private void UpdateAllBindings()
    {
        if (_viewModel == null) return;

    }

    /// <summary>
    /// Apply VM state from JSON for snapshot rendering.
    /// This allows setting UI state without a full ViewModel implementation.
    /// </summary>
    public void ApplyVmJson(string json)
    {
        if (string.IsNullOrEmpty(json)) return;

        try
        {
            var doc = System.Text.Json.JsonDocument.Parse(json);
            ApplyVmFromJsonElement(doc.RootElement);
        }
        catch (System.Text.Json.JsonException ex)
        {
            GD.PrintErr($"ApplyVmJson failed to parse JSON: {ex.Message}");
        }
    }

    private void ApplyVmFromJsonElement(System.Text.Json.JsonElement element, string prefix = "")
    {
        if (element.ValueKind != System.Text.Json.JsonValueKind.Object) return;

        foreach (var prop in element.EnumerateObject())
        {
            var path = string.IsNullOrEmpty(prefix) ? prop.Name : $"{prefix}.{prop.Name}";

            if (prop.Value.ValueKind == System.Text.Json.JsonValueKind.Object)
            {
                ApplyVmFromJsonElement(prop.Value, path);
            }
            else
            {
                ApplyVmProperty(path, prop.Value);
            }
        }
    }

    private void ApplyVmProperty(string path, System.Text.Json.JsonElement value)
    {
        // No bindings defined
        _ = path; _ = value;
    }

    // Component accessors
    public VBoxContainer Agentlistpanel => _agentlistpanel;
    public HBoxContainer Header => _header;
    public Label Headerlabel => _headerlabel;
    public VBoxContainer Scrollarea => _scrollarea;
    public VBoxContainer Agentlist => _agentlist;
}
