// <auto-generated>
// Generated by BoomHud.Gen.Godot from Agentlistentry
// </auto-generated>

#nullable enable

using Godot;
using System;
using System.ComponentModel;

namespace GiantIsopod.Hosts.CompleteApp;

public partial class AgentlistentryView : HBoxContainer
{
    public const string BoomHudSourceId = "sha256:d15614d6167f7e10fce41eb4c928ae24ad031ce08f7ac6d2f3453986d8a10c88";
    public const string BoomHudContractId = "";
    public static readonly string[] BoomHudNormalizedPseudoNodes = new string[0];

    private IAgentlistentryViewModel? _viewModel;

    // Control references
    private HBoxContainer _agentlistentry = null!;
    private PanelContainer _statusdot = null!;
    private Label _namelabel = null!;
    private Label _statelabel = null!;
    private Control _spacer = null!;
    private Label _removebutton = null!;

    public override void _Ready()
    {
        base._Ready();
        BindUiFromScene();
        InitializeUiFromScene();
    }

    private void BindUiFromScene()
    {
        _agentlistentry = this;
        _statusdot = GetNode<PanelContainer>("statusdot");
        _namelabel = GetNode<Label>("namelabel");
        _statelabel = GetNode<Label>("statelabel");
        _spacer = GetNode<Control>("spacer");
        _removebutton = GetNode<Label>("removebutton");
    }

    private void InitializeUiFromScene()
    {
        {
        if ((object)this is Control c)
        {
            c.CustomMinimumSize = new Vector2(224, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 28);
        }
        }
        this.AddThemeConstantOverride("separation", 8);
        this.AddThemeConstantOverride("h_separation", 8);
        this.AddThemeConstantOverride("v_separation", 8);
        this.AddThemeConstantOverride("margin_left", 8);
        this.AddThemeConstantOverride("margin_top", 4);
        this.AddThemeConstantOverride("margin_right", 8);
        this.AddThemeConstantOverride("margin_bottom", 4);

        {
        if ((object)_statusdot is Control c)
        {
            c.CustomMinimumSize = new Vector2(8, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 8);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkCenter;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }

        _namelabel.AddThemeColorOverride("font_color", new Color(0.84705883f, 0.84705883f, 0.8980392f, 1f));
        _namelabel.Set("text", "agent-1");

        _statelabel.AddThemeColorOverride("font_color", new Color(0.49803922f, 0.49803922f, 0.54901963f, 1f));
        _statelabel.Set("text", "idle");


        _removebutton.AddThemeColorOverride("font_color", new Color(0.6f, 0.29803923f, 0.29803923f, 1f));
        _removebutton.Set("text", "x");
    }

    private void BuildUi()
    {
        {
        if ((object)this is Control c)
        {
            c.CustomMinimumSize = new Vector2(224, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 28);
        }
        }
        this.AddThemeConstantOverride("separation", 8);
        this.AddThemeConstantOverride("h_separation", 8);
        this.AddThemeConstantOverride("v_separation", 8);
        this.AddThemeConstantOverride("margin_left", 8);
        this.AddThemeConstantOverride("margin_top", 4);
        this.AddThemeConstantOverride("margin_right", 8);
        this.AddThemeConstantOverride("margin_bottom", 4);

        _statusdot = new PanelContainer();
        _statusdot.Name = "statusdot";
        {
        if ((object)_statusdot is Control c)
        {
            c.CustomMinimumSize = new Vector2(8, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 8);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkCenter;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        this.AddChild(_statusdot);

        _namelabel = new Label();
        _namelabel.Name = "namelabel";
        _namelabel.AddThemeColorOverride("font_color", new Color(0.84705883f, 0.84705883f, 0.8980392f, 1f));
        _namelabel.Set("text", "agent-1");
        this.AddChild(_namelabel);

        _statelabel = new Label();
        _statelabel.Name = "statelabel";
        _statelabel.AddThemeColorOverride("font_color", new Color(0.49803922f, 0.49803922f, 0.54901963f, 1f));
        _statelabel.Set("text", "idle");
        this.AddChild(_statelabel);

        _spacer = new Control();
        _spacer.Name = "spacer";
        this.AddChild(_spacer);

        _removebutton = new Label();
        _removebutton.Name = "removebutton";
        _removebutton.AddThemeColorOverride("font_color", new Color(0.6f, 0.29803923f, 0.29803923f, 1f));
        _removebutton.Set("text", "x");
        this.AddChild(_removebutton);
    }

    public void SetViewModel(IAgentlistentryViewModel? viewModel)
    {
        if (_viewModel != null)
        {
            _viewModel.PropertyChanged -= OnViewModelPropertyChanged;
        }

        _viewModel = viewModel;

        if (_viewModel != null)
        {
            _viewModel.PropertyChanged += OnViewModelPropertyChanged;
            UpdateAllBindings();
        }
    }

    private void OnViewModelPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (_viewModel == null) return;

    }

    private void UpdateAllBindings()
    {
        if (_viewModel == null) return;

    }

    /// <summary>
    /// Apply VM state from JSON for snapshot rendering.
    /// This allows setting UI state without a full ViewModel implementation.
    /// </summary>
    public void ApplyVmJson(string json)
    {
        if (string.IsNullOrEmpty(json)) return;

        try
        {
            var doc = System.Text.Json.JsonDocument.Parse(json);
            ApplyVmFromJsonElement(doc.RootElement);
        }
        catch (System.Text.Json.JsonException ex)
        {
            GD.PrintErr($"ApplyVmJson failed to parse JSON: {ex.Message}");
        }
    }

    private void ApplyVmFromJsonElement(System.Text.Json.JsonElement element, string prefix = "")
    {
        if (element.ValueKind != System.Text.Json.JsonValueKind.Object) return;

        foreach (var prop in element.EnumerateObject())
        {
            var path = string.IsNullOrEmpty(prefix) ? prop.Name : $"{prefix}.{prop.Name}";

            if (prop.Value.ValueKind == System.Text.Json.JsonValueKind.Object)
            {
                ApplyVmFromJsonElement(prop.Value, path);
            }
            else
            {
                ApplyVmProperty(path, prop.Value);
            }
        }
    }

    private void ApplyVmProperty(string path, System.Text.Json.JsonElement value)
    {
        // No bindings defined
        _ = path; _ = value;
    }

    // Component accessors
    public HBoxContainer Agentlistentry => _agentlistentry;
    public PanelContainer Statusdot => _statusdot;
    public Label Namelabel => _namelabel;
    public Label Statelabel => _statelabel;
    public Control Spacer => _spacer;
    public Label Removebutton => _removebutton;
}
