// <auto-generated>
// Generated by BoomHud.Gen.Godot from Consolepanel
// </auto-generated>

#nullable enable

using Godot;
using System;
using System.ComponentModel;

namespace GiantIsopod.Hosts.CompleteApp;

public partial class ConsolepanelView : VBoxContainer
{
    public const string BoomHudSourceId = "sha256:9033091eba7c537cc1048646a953ecacd140f4d7a76ccfca09aea04eb0537936";
    public const string BoomHudContractId = "";
    public static readonly string[] BoomHudNormalizedPseudoNodes = new string[0];

    private IConsolepanelViewModel? _viewModel;

    // Control references
    private VBoxContainer _consolepanel = null!;
    private HBoxContainer _consoleheader = null!;
    private Label _consoletitle = null!;
    private Control _tabspacer = null!;
    private Label _terminaltabbtn = null!;
    private Label _renderedtabbtn = null!;
    private Control _headerspacer = null!;
    private Label _closebtn = null!;
    private VBoxContainer _consolebody = null!;
    private VBoxContainer _terminalcontainer = null!;

    public override void _Ready()
    {
        base._Ready();
        BindUiFromScene();
        InitializeUiFromScene();
    }

    private void BindUiFromScene()
    {
        _consolepanel = this;
        _consoleheader = GetNode<HBoxContainer>("consoleheader");
        _consoletitle = GetNode<Label>("consoleheader/consoletitle");
        _tabspacer = GetNode<Control>("consoleheader/tabspacer");
        _terminaltabbtn = GetNode<Label>("consoleheader/terminaltabbtn");
        _renderedtabbtn = GetNode<Label>("consoleheader/renderedtabbtn");
        _headerspacer = GetNode<Control>("consoleheader/headerspacer");
        _closebtn = GetNode<Label>("consoleheader/closebtn");
        _consolebody = GetNode<VBoxContainer>("consolebody");
        _terminalcontainer = GetNode<VBoxContainer>("consolebody/terminalcontainer");
    }

    private void InitializeUiFromScene()
    {
        {
        if ((object)this is Control c)
        {
            c.CustomMinimumSize = new Vector2(1920, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 350);
        }
        }
        this.AddThemeConstantOverride("separation", 0);
        this.AddThemeConstantOverride("h_separation", 0);
        this.AddThemeConstantOverride("v_separation", 0);

        {
        if ((object)_consoleheader is Control c)
        {
            c.CustomMinimumSize = new Vector2(1920, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 30);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkBegin;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        _consoleheader.AddThemeConstantOverride("separation", 8);
        _consoleheader.AddThemeConstantOverride("h_separation", 8);
        _consoleheader.AddThemeConstantOverride("v_separation", 8);
        _consoleheader.AddThemeConstantOverride("margin_left", 12);
        _consoleheader.AddThemeConstantOverride("margin_top", 6);
        _consoleheader.AddThemeConstantOverride("margin_right", 12);
        _consoleheader.AddThemeConstantOverride("margin_bottom", 6);

        _consoletitle.AddThemeColorOverride("font_color", new Color(0.8f, 0.8f, 0.84705883f, 1f));
        _consoletitle.Set("text", "Console");


        _terminaltabbtn.AddThemeColorOverride("font_color", new Color(0.69803923f, 0.69803923f, 0.7490196f, 1f));
        _terminaltabbtn.Set("text", "Terminal");

        _renderedtabbtn.AddThemeColorOverride("font_color", new Color(0.49803922f, 0.49803922f, 0.54901963f, 1f));
        _renderedtabbtn.Set("text", "Rendered");


        _closebtn.AddThemeColorOverride("font_color", new Color(0.6f, 0.6f, 0.64705884f, 1f));
        _closebtn.Set("text", "x");

        {
        if ((object)_consolebody is Control c)
        {
            c.CustomMinimumSize = new Vector2(1920, c.CustomMinimumSize.Y);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkBegin;
            c.SizeFlagsVertical = Control.SizeFlags.ExpandFill;
        }
        }

        {
        if ((object)_terminalcontainer is Control c)
        {
            c.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
            c.SizeFlagsVertical = Control.SizeFlags.ExpandFill;
        }
        }
    }

    private void BuildUi()
    {
        {
        if ((object)this is Control c)
        {
            c.CustomMinimumSize = new Vector2(1920, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 350);
        }
        }
        this.AddThemeConstantOverride("separation", 0);
        this.AddThemeConstantOverride("h_separation", 0);
        this.AddThemeConstantOverride("v_separation", 0);

        _consoleheader = new HBoxContainer();
        _consoleheader.Name = "consoleheader";
        {
        if ((object)_consoleheader is Control c)
        {
            c.CustomMinimumSize = new Vector2(1920, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 30);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkBegin;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        _consoleheader.AddThemeConstantOverride("separation", 8);
        _consoleheader.AddThemeConstantOverride("h_separation", 8);
        _consoleheader.AddThemeConstantOverride("v_separation", 8);
        _consoleheader.AddThemeConstantOverride("margin_left", 12);
        _consoleheader.AddThemeConstantOverride("margin_top", 6);
        _consoleheader.AddThemeConstantOverride("margin_right", 12);
        _consoleheader.AddThemeConstantOverride("margin_bottom", 6);
        this.AddChild(_consoleheader);

        _consoletitle = new Label();
        _consoletitle.Name = "consoletitle";
        _consoletitle.AddThemeColorOverride("font_color", new Color(0.8f, 0.8f, 0.84705883f, 1f));
        _consoletitle.Set("text", "Console");
        _consoleheader.AddChild(_consoletitle);

        _tabspacer = new Control();
        _tabspacer.Name = "tabspacer";
        _consoleheader.AddChild(_tabspacer);

        _terminaltabbtn = new Label();
        _terminaltabbtn.Name = "terminaltabbtn";
        _terminaltabbtn.AddThemeColorOverride("font_color", new Color(0.69803923f, 0.69803923f, 0.7490196f, 1f));
        _terminaltabbtn.Set("text", "Terminal");
        _consoleheader.AddChild(_terminaltabbtn);

        _renderedtabbtn = new Label();
        _renderedtabbtn.Name = "renderedtabbtn";
        _renderedtabbtn.AddThemeColorOverride("font_color", new Color(0.49803922f, 0.49803922f, 0.54901963f, 1f));
        _renderedtabbtn.Set("text", "Rendered");
        _consoleheader.AddChild(_renderedtabbtn);

        _headerspacer = new Control();
        _headerspacer.Name = "headerspacer";
        _consoleheader.AddChild(_headerspacer);

        _closebtn = new Label();
        _closebtn.Name = "closebtn";
        _closebtn.AddThemeColorOverride("font_color", new Color(0.6f, 0.6f, 0.64705884f, 1f));
        _closebtn.Set("text", "x");
        _consoleheader.AddChild(_closebtn);

        _consolebody = new VBoxContainer();
        _consolebody.Name = "consolebody";
        {
        if ((object)_consolebody is Control c)
        {
            c.CustomMinimumSize = new Vector2(1920, c.CustomMinimumSize.Y);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkBegin;
            c.SizeFlagsVertical = Control.SizeFlags.ExpandFill;
        }
        }
        this.AddChild(_consolebody);

        _terminalcontainer = new VBoxContainer();
        _terminalcontainer.Name = "terminalcontainer";
        {
        if ((object)_terminalcontainer is Control c)
        {
            c.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
            c.SizeFlagsVertical = Control.SizeFlags.ExpandFill;
        }
        }
        _consolebody.AddChild(_terminalcontainer);
    }

    public void SetViewModel(IConsolepanelViewModel? viewModel)
    {
        if (_viewModel != null)
        {
            _viewModel.PropertyChanged -= OnViewModelPropertyChanged;
        }

        _viewModel = viewModel;

        if (_viewModel != null)
        {
            _viewModel.PropertyChanged += OnViewModelPropertyChanged;
            UpdateAllBindings();
        }
    }

    private void OnViewModelPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (_viewModel == null) return;

    }

    private void UpdateAllBindings()
    {
        if (_viewModel == null) return;

    }

    /// <summary>
    /// Apply VM state from JSON for snapshot rendering.
    /// This allows setting UI state without a full ViewModel implementation.
    /// </summary>
    public void ApplyVmJson(string json)
    {
        if (string.IsNullOrEmpty(json)) return;

        try
        {
            var doc = System.Text.Json.JsonDocument.Parse(json);
            ApplyVmFromJsonElement(doc.RootElement);
        }
        catch (System.Text.Json.JsonException ex)
        {
            GD.PrintErr($"ApplyVmJson failed to parse JSON: {ex.Message}");
        }
    }

    private void ApplyVmFromJsonElement(System.Text.Json.JsonElement element, string prefix = "")
    {
        if (element.ValueKind != System.Text.Json.JsonValueKind.Object) return;

        foreach (var prop in element.EnumerateObject())
        {
            var path = string.IsNullOrEmpty(prefix) ? prop.Name : $"{prefix}.{prop.Name}";

            if (prop.Value.ValueKind == System.Text.Json.JsonValueKind.Object)
            {
                ApplyVmFromJsonElement(prop.Value, path);
            }
            else
            {
                ApplyVmProperty(path, prop.Value);
            }
        }
    }

    private void ApplyVmProperty(string path, System.Text.Json.JsonElement value)
    {
        // No bindings defined
        _ = path; _ = value;
    }

    // Component accessors
    public VBoxContainer Consolepanel => _consolepanel;
    public HBoxContainer Consoleheader => _consoleheader;
    public Label Consoletitle => _consoletitle;
    public Control Tabspacer => _tabspacer;
    public Label Terminaltabbtn => _terminaltabbtn;
    public Label Renderedtabbtn => _renderedtabbtn;
    public Control Headerspacer => _headerspacer;
    public Label Closebtn => _closebtn;
    public VBoxContainer Consolebody => _consolebody;
    public VBoxContainer Terminalcontainer => _terminalcontainer;
}
