// <auto-generated>
// Generated by BoomHud.Gen.Godot from Agentlistentry
// </auto-generated>

#nullable enable

namespace GiantIsopod.Hosts.CompleteApp;

using System.ComponentModel;

/// <summary>
/// ViewModel interface for Agentlistentry.
/// </summary>
public interface IAgentlistentryViewModel : INotifyPropertyChanged
{
}
