// <auto-generated>
// Generated by BoomHud.Gen.Godot from Agentlistpanel
// </auto-generated>

#nullable enable

namespace GiantIsopod.Hosts.CompleteApp;

using System.ComponentModel;

/// <summary>
/// ViewModel interface for Agentlistpanel.
/// </summary>
public interface IAgentlistpanelViewModel : INotifyPropertyChanged
{
}
