// <auto-generated>
// Generated by BoomHud.Gen.Godot from Consolepanel
// </auto-generated>

#nullable enable

namespace GiantIsopod.Hosts.CompleteApp;

using System.ComponentModel;

/// <summary>
/// ViewModel interface for Consolepanel.
/// </summary>
public interface IConsolepanelViewModel : INotifyPropertyChanged
{
}
