// <auto-generated>
// Generated by BoomHud.Gen.Godot from Spawncontrols
// </auto-generated>

#nullable enable

namespace GiantIsopod.Hosts.CompleteApp;

using System.ComponentModel;

/// <summary>
/// ViewModel interface for Spawncontrols.
/// </summary>
public interface ISpawncontrolsViewModel : INotifyPropertyChanged
{
}
