// <auto-generated>
// Generated by BoomHud.Gen.Godot from Swarmhud
// </auto-generated>

#nullable enable

namespace GiantIsopod.Hosts.CompleteApp;

using System.ComponentModel;

/// <summary>
/// ViewModel interface for Swarmhud.
/// </summary>
public interface ISwarmhudViewModel : INotifyPropertyChanged
{
}
