// <auto-generated>
// Generated by BoomHud.Gen.Godot from Swarmtopbar
// </auto-generated>

#nullable enable

namespace GiantIsopod.Hosts.CompleteApp;

using System.ComponentModel;

/// <summary>
/// ViewModel interface for Swarmtopbar.
/// </summary>
public interface ISwarmtopbarViewModel : INotifyPropertyChanged
{
}
