// <auto-generated>
// Generated by BoomHud.Gen.Godot from Spawncontrols
// </auto-generated>

#nullable enable

using Godot;
using System;
using System.ComponentModel;

namespace GiantIsopod.Hosts.CompleteApp;

public partial class SpawncontrolsView : HBoxContainer
{
    public const string BoomHudSourceId = "sha256:7446f83259e5498fca3dcd333dfab11112e9932dbfce4ee1270741f20445162d";
    public const string BoomHudContractId = "";
    public static readonly string[] BoomHudNormalizedPseudoNodes = new string[0];

    private ISpawncontrolsViewModel? _viewModel;

    // Control references
    private HBoxContainer _spawncontrols = null!;
    private HBoxContainer _runtimedropdown = null!;
    private Label _dropdownlabel = null!;
    private HBoxContainer _createbutton = null!;
    private Label _createlabel = null!;

    public override void _Ready()
    {
        base._Ready();
        BindUiFromScene();
        InitializeUiFromScene();
    }

    private void BindUiFromScene()
    {
        _spawncontrols = this;
        _runtimedropdown = GetNode<HBoxContainer>("runtimedropdown");
        _dropdownlabel = GetNode<Label>("runtimedropdown/dropdownlabel");
        _createbutton = GetNode<HBoxContainer>("createbutton");
        _createlabel = GetNode<Label>("createbutton/createlabel");
    }

    private void InitializeUiFromScene()
    {
        {
        if ((object)this is Control c)
        {
            c.CustomMinimumSize = new Vector2(280, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 36);
        }
        }
        this.AddThemeConstantOverride("separation", 8);
        this.AddThemeConstantOverride("h_separation", 8);
        this.AddThemeConstantOverride("v_separation", 8);
        this.AddThemeConstantOverride("margin_left", 12);
        this.AddThemeConstantOverride("margin_top", 6);
        this.AddThemeConstantOverride("margin_right", 12);
        this.AddThemeConstantOverride("margin_bottom", 6);

        {
        if ((object)_runtimedropdown is Control c)
        {
            c.CustomMinimumSize = new Vector2(160, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 24);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkCenter;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }

        _dropdownlabel.AddThemeColorOverride("font_color", new Color(0.69803923f, 0.69803923f, 0.7490196f, 1f));
        _dropdownlabel.Set("text", "Select runtime...");

        {
        if ((object)_createbutton is Control c)
        {
            c.CustomMinimumSize = new Vector2(80, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 24);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkCenter;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }

        _createlabel.AddThemeColorOverride("font_color", new Color(0.8980392f, 0.9490196f, 0.8980392f, 1f));
        _createlabel.Set("text", "+ Spawn");
    }

    private void BuildUi()
    {
        {
        if ((object)this is Control c)
        {
            c.CustomMinimumSize = new Vector2(280, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 36);
        }
        }
        this.AddThemeConstantOverride("separation", 8);
        this.AddThemeConstantOverride("h_separation", 8);
        this.AddThemeConstantOverride("v_separation", 8);
        this.AddThemeConstantOverride("margin_left", 12);
        this.AddThemeConstantOverride("margin_top", 6);
        this.AddThemeConstantOverride("margin_right", 12);
        this.AddThemeConstantOverride("margin_bottom", 6);

        _runtimedropdown = new HBoxContainer();
        _runtimedropdown.Name = "runtimedropdown";
        {
        if ((object)_runtimedropdown is Control c)
        {
            c.CustomMinimumSize = new Vector2(160, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 24);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkCenter;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        this.AddChild(_runtimedropdown);

        _dropdownlabel = new Label();
        _dropdownlabel.Name = "dropdownlabel";
        _dropdownlabel.AddThemeColorOverride("font_color", new Color(0.69803923f, 0.69803923f, 0.7490196f, 1f));
        _dropdownlabel.Set("text", "Select runtime...");
        _runtimedropdown.AddChild(_dropdownlabel);

        _createbutton = new HBoxContainer();
        _createbutton.Name = "createbutton";
        {
        if ((object)_createbutton is Control c)
        {
            c.CustomMinimumSize = new Vector2(80, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 24);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkCenter;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        this.AddChild(_createbutton);

        _createlabel = new Label();
        _createlabel.Name = "createlabel";
        _createlabel.AddThemeColorOverride("font_color", new Color(0.8980392f, 0.9490196f, 0.8980392f, 1f));
        _createlabel.Set("text", "+ Spawn");
        _createbutton.AddChild(_createlabel);
    }

    public void SetViewModel(ISpawncontrolsViewModel? viewModel)
    {
        if (_viewModel != null)
        {
            _viewModel.PropertyChanged -= OnViewModelPropertyChanged;
        }

        _viewModel = viewModel;

        if (_viewModel != null)
        {
            _viewModel.PropertyChanged += OnViewModelPropertyChanged;
            UpdateAllBindings();
        }
    }

    private void OnViewModelPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (_viewModel == null) return;

    }

    private void UpdateAllBindings()
    {
        if (_viewModel == null) return;

    }

    /// <summary>
    /// Apply VM state from JSON for snapshot rendering.
    /// This allows setting UI state without a full ViewModel implementation.
    /// </summary>
    public void ApplyVmJson(string json)
    {
        if (string.IsNullOrEmpty(json)) return;

        try
        {
            var doc = System.Text.Json.JsonDocument.Parse(json);
            ApplyVmFromJsonElement(doc.RootElement);
        }
        catch (System.Text.Json.JsonException ex)
        {
            GD.PrintErr($"ApplyVmJson failed to parse JSON: {ex.Message}");
        }
    }

    private void ApplyVmFromJsonElement(System.Text.Json.JsonElement element, string prefix = "")
    {
        if (element.ValueKind != System.Text.Json.JsonValueKind.Object) return;

        foreach (var prop in element.EnumerateObject())
        {
            var path = string.IsNullOrEmpty(prefix) ? prop.Name : $"{prefix}.{prop.Name}";

            if (prop.Value.ValueKind == System.Text.Json.JsonValueKind.Object)
            {
                ApplyVmFromJsonElement(prop.Value, path);
            }
            else
            {
                ApplyVmProperty(path, prop.Value);
            }
        }
    }

    private void ApplyVmProperty(string path, System.Text.Json.JsonElement value)
    {
        // No bindings defined
        _ = path; _ = value;
    }

    // Component accessors
    public HBoxContainer Spawncontrols => _spawncontrols;
    public HBoxContainer Runtimedropdown => _runtimedropdown;
    public Label Dropdownlabel => _dropdownlabel;
    public HBoxContainer Createbutton => _createbutton;
    public Label Createlabel => _createlabel;
}
