// <auto-generated>
// Generated by BoomHud.Gen.Godot from Swarmhud
// </auto-generated>

#nullable enable

using Godot;
using System;
using System.ComponentModel;

namespace GiantIsopod.Hosts.CompleteApp;

public partial class SwarmhudView : VBoxContainer
{
    public const string BoomHudSourceId = "sha256:f95f26c0830178c62e44d2af8439bf7056defe12c5467d136d14694aeb11f100";
    public const string BoomHudContractId = "";
    public static readonly string[] BoomHudNormalizedPseudoNodes = new string[0];

    private ISwarmhudViewModel? _viewModel;

    // Control references
    private VBoxContainer _swarmhud = null!;
    private HBoxContainer _topbarslot = null!;
    private HBoxContainer _middlerow = null!;
    private VBoxContainer _leftcolumn = null!;
    private HBoxContainer _spawncontrolsslot = null!;
    private VBoxContainer _centerarea = null!;
    private HBoxContainer _centerheader = null!;
    private Label _genuitabbtn = null!;
    private Control _tabspacer = null!;
    private Label _taskgraphtabbtn = null!;
    private VBoxContainer _centerbody = null!;
    private VBoxContainer _genuihost = null!;
    private VBoxContainer _rightcolumn = null!;
    private VBoxContainer _agentpanelslot = null!;
    private VBoxContainer _consolepanelslot = null!;

    public override void _Ready()
    {
        base._Ready();
        BindUiFromScene();
        InitializeUiFromScene();
    }

    private void BindUiFromScene()
    {
        _swarmhud = this;
        _topbarslot = GetNode<HBoxContainer>("topbarslot");
        _middlerow = GetNode<HBoxContainer>("middlerow");
        _leftcolumn = GetNode<VBoxContainer>("middlerow/leftcolumn");
        _spawncontrolsslot = GetNode<HBoxContainer>("middlerow/leftcolumn/spawncontrolsslot");
        _centerarea = GetNode<VBoxContainer>("middlerow/centerarea");
        _centerheader = GetNode<HBoxContainer>("middlerow/centerarea/centerheader");
        _genuitabbtn = GetNode<Label>("middlerow/centerarea/centerheader/genuitabbtn");
        _tabspacer = GetNode<Control>("middlerow/centerarea/centerheader/tabspacer");
        _taskgraphtabbtn = GetNode<Label>("middlerow/centerarea/centerheader/taskgraphtabbtn");
        _centerbody = GetNode<VBoxContainer>("middlerow/centerarea/centerbody");
        _genuihost = GetNode<VBoxContainer>("middlerow/centerarea/centerbody/genuihost");
        _rightcolumn = GetNode<VBoxContainer>("middlerow/rightcolumn");
        _agentpanelslot = GetNode<VBoxContainer>("middlerow/rightcolumn/agentpanelslot");
        _consolepanelslot = GetNode<VBoxContainer>("consolepanelslot");
    }

    private void InitializeUiFromScene()
    {
        {
        if ((object)this is Control c)
        {
            c.CustomMinimumSize = new Vector2(1920, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 1080);
        }
        }
        this.AddThemeConstantOverride("separation", 0);
        this.AddThemeConstantOverride("h_separation", 0);
        this.AddThemeConstantOverride("v_separation", 0);

        {
        if ((object)_topbarslot is Control c)
        {
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 32);
            c.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }

        {
        if ((object)_middlerow is Control c)
        {
            c.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
            c.SizeFlagsVertical = Control.SizeFlags.ExpandFill;
        }
        }
        _middlerow.AddThemeConstantOverride("separation", 0);
        _middlerow.AddThemeConstantOverride("h_separation", 0);
        _middlerow.AddThemeConstantOverride("v_separation", 0);

        {
        if ((object)_leftcolumn is Control c)
        {
            c.CustomMinimumSize = new Vector2(300, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 698);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkBegin;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        _leftcolumn.AddThemeConstantOverride("separation", 8);
        _leftcolumn.AddThemeConstantOverride("h_separation", 8);
        _leftcolumn.AddThemeConstantOverride("v_separation", 8);
        _leftcolumn.AddThemeConstantOverride("margin_left", 12);
        _leftcolumn.AddThemeConstantOverride("margin_top", 8);
        _leftcolumn.AddThemeConstantOverride("margin_right", 0);
        _leftcolumn.AddThemeConstantOverride("margin_bottom", 0);

        {
        if ((object)_spawncontrolsslot is Control c)
        {
            c.CustomMinimumSize = new Vector2(280, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 36);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkCenter;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }

        {
        if ((object)_centerarea is Control c)
        {
            c.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
            c.SizeFlagsVertical = Control.SizeFlags.ExpandFill;
        }
        }

        {
        if ((object)_centerheader is Control c)
        {
            c.CustomMinimumSize = new Vector2(1380, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 30);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkBegin;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        _centerheader.AddThemeConstantOverride("separation", 8);
        _centerheader.AddThemeConstantOverride("h_separation", 8);
        _centerheader.AddThemeConstantOverride("v_separation", 8);
        _centerheader.AddThemeConstantOverride("margin_left", 12);
        _centerheader.AddThemeConstantOverride("margin_top", 6);
        _centerheader.AddThemeConstantOverride("margin_right", 12);
        _centerheader.AddThemeConstantOverride("margin_bottom", 6);

        _genuitabbtn.AddThemeColorOverride("font_color", new Color(0.69803923f, 0.69803923f, 0.7490196f, 1f));
        _genuitabbtn.Set("text", "GenUI");


        _taskgraphtabbtn.AddThemeColorOverride("font_color", new Color(0.49803922f, 0.49803922f, 0.54901963f, 1f));
        _taskgraphtabbtn.Set("text", "Task Graph");

        {
        if ((object)_centerbody is Control c)
        {
            c.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
            c.SizeFlagsVertical = Control.SizeFlags.ExpandFill;
        }
        }

        {
        if ((object)_genuihost is Control c)
        {
            c.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
            c.SizeFlagsVertical = Control.SizeFlags.ExpandFill;
        }
        }

        {
        if ((object)_rightcolumn is Control c)
        {
            c.CustomMinimumSize = new Vector2(240, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 698);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkCenter;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }

        {
        if ((object)_agentpanelslot is Control c)
        {
            c.CustomMinimumSize = new Vector2(240, c.CustomMinimumSize.Y);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkCenter;
            c.SizeFlagsVertical = Control.SizeFlags.ExpandFill;
        }
        }

        {
        if ((object)_consolepanelslot is Control c)
        {
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 350);
            c.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
    }

    private void BuildUi()
    {
        {
        if ((object)this is Control c)
        {
            c.CustomMinimumSize = new Vector2(1920, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 1080);
        }
        }
        this.AddThemeConstantOverride("separation", 0);
        this.AddThemeConstantOverride("h_separation", 0);
        this.AddThemeConstantOverride("v_separation", 0);

        _topbarslot = new HBoxContainer();
        _topbarslot.Name = "topbarslot";
        {
        if ((object)_topbarslot is Control c)
        {
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 32);
            c.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        this.AddChild(_topbarslot);

        _middlerow = new HBoxContainer();
        _middlerow.Name = "middlerow";
        {
        if ((object)_middlerow is Control c)
        {
            c.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
            c.SizeFlagsVertical = Control.SizeFlags.ExpandFill;
        }
        }
        _middlerow.AddThemeConstantOverride("separation", 0);
        _middlerow.AddThemeConstantOverride("h_separation", 0);
        _middlerow.AddThemeConstantOverride("v_separation", 0);
        this.AddChild(_middlerow);

        _leftcolumn = new VBoxContainer();
        _leftcolumn.Name = "leftcolumn";
        {
        if ((object)_leftcolumn is Control c)
        {
            c.CustomMinimumSize = new Vector2(300, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 698);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkBegin;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        _leftcolumn.AddThemeConstantOverride("separation", 8);
        _leftcolumn.AddThemeConstantOverride("h_separation", 8);
        _leftcolumn.AddThemeConstantOverride("v_separation", 8);
        _leftcolumn.AddThemeConstantOverride("margin_left", 12);
        _leftcolumn.AddThemeConstantOverride("margin_top", 8);
        _leftcolumn.AddThemeConstantOverride("margin_right", 0);
        _leftcolumn.AddThemeConstantOverride("margin_bottom", 0);
        _middlerow.AddChild(_leftcolumn);

        _spawncontrolsslot = new HBoxContainer();
        _spawncontrolsslot.Name = "spawncontrolsslot";
        {
        if ((object)_spawncontrolsslot is Control c)
        {
            c.CustomMinimumSize = new Vector2(280, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 36);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkCenter;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        _leftcolumn.AddChild(_spawncontrolsslot);

        _centerarea = new VBoxContainer();
        _centerarea.Name = "centerarea";
        {
        if ((object)_centerarea is Control c)
        {
            c.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
            c.SizeFlagsVertical = Control.SizeFlags.ExpandFill;
        }
        }
        _middlerow.AddChild(_centerarea);

        _centerheader = new HBoxContainer();
        _centerheader.Name = "centerheader";
        {
        if ((object)_centerheader is Control c)
        {
            c.CustomMinimumSize = new Vector2(1380, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 30);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkBegin;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        _centerheader.AddThemeConstantOverride("separation", 8);
        _centerheader.AddThemeConstantOverride("h_separation", 8);
        _centerheader.AddThemeConstantOverride("v_separation", 8);
        _centerheader.AddThemeConstantOverride("margin_left", 12);
        _centerheader.AddThemeConstantOverride("margin_top", 6);
        _centerheader.AddThemeConstantOverride("margin_right", 12);
        _centerheader.AddThemeConstantOverride("margin_bottom", 6);
        _centerarea.AddChild(_centerheader);

        _genuitabbtn = new Label();
        _genuitabbtn.Name = "genuitabbtn";
        _genuitabbtn.AddThemeColorOverride("font_color", new Color(0.69803923f, 0.69803923f, 0.7490196f, 1f));
        _genuitabbtn.Set("text", "GenUI");
        _centerheader.AddChild(_genuitabbtn);

        _tabspacer = new Control();
        _tabspacer.Name = "tabspacer";
        _centerheader.AddChild(_tabspacer);

        _taskgraphtabbtn = new Label();
        _taskgraphtabbtn.Name = "taskgraphtabbtn";
        _taskgraphtabbtn.AddThemeColorOverride("font_color", new Color(0.49803922f, 0.49803922f, 0.54901963f, 1f));
        _taskgraphtabbtn.Set("text", "Task Graph");
        _centerheader.AddChild(_taskgraphtabbtn);

        _centerbody = new VBoxContainer();
        _centerbody.Name = "centerbody";
        {
        if ((object)_centerbody is Control c)
        {
            c.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
            c.SizeFlagsVertical = Control.SizeFlags.ExpandFill;
        }
        }
        _centerarea.AddChild(_centerbody);

        _genuihost = new VBoxContainer();
        _genuihost.Name = "genuihost";
        {
        if ((object)_genuihost is Control c)
        {
            c.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
            c.SizeFlagsVertical = Control.SizeFlags.ExpandFill;
        }
        }
        _centerbody.AddChild(_genuihost);

        _rightcolumn = new VBoxContainer();
        _rightcolumn.Name = "rightcolumn";
        {
        if ((object)_rightcolumn is Control c)
        {
            c.CustomMinimumSize = new Vector2(240, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 698);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkCenter;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        _middlerow.AddChild(_rightcolumn);

        _agentpanelslot = new VBoxContainer();
        _agentpanelslot.Name = "agentpanelslot";
        {
        if ((object)_agentpanelslot is Control c)
        {
            c.CustomMinimumSize = new Vector2(240, c.CustomMinimumSize.Y);
            c.SizeFlagsHorizontal = Control.SizeFlags.ShrinkCenter;
            c.SizeFlagsVertical = Control.SizeFlags.ExpandFill;
        }
        }
        _rightcolumn.AddChild(_agentpanelslot);

        _consolepanelslot = new VBoxContainer();
        _consolepanelslot.Name = "consolepanelslot";
        {
        if ((object)_consolepanelslot is Control c)
        {
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 350);
            c.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
            c.SizeFlagsVertical = Control.SizeFlags.ShrinkCenter;
        }
        }
        this.AddChild(_consolepanelslot);
    }

    public void SetViewModel(ISwarmhudViewModel? viewModel)
    {
        if (_viewModel != null)
        {
            _viewModel.PropertyChanged -= OnViewModelPropertyChanged;
        }

        _viewModel = viewModel;

        if (_viewModel != null)
        {
            _viewModel.PropertyChanged += OnViewModelPropertyChanged;
            UpdateAllBindings();
        }
    }

    private void OnViewModelPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (_viewModel == null) return;

    }

    private void UpdateAllBindings()
    {
        if (_viewModel == null) return;

    }

    /// <summary>
    /// Apply VM state from JSON for snapshot rendering.
    /// This allows setting UI state without a full ViewModel implementation.
    /// </summary>
    public void ApplyVmJson(string json)
    {
        if (string.IsNullOrEmpty(json)) return;

        try
        {
            var doc = System.Text.Json.JsonDocument.Parse(json);
            ApplyVmFromJsonElement(doc.RootElement);
        }
        catch (System.Text.Json.JsonException ex)
        {
            GD.PrintErr($"ApplyVmJson failed to parse JSON: {ex.Message}");
        }
    }

    private void ApplyVmFromJsonElement(System.Text.Json.JsonElement element, string prefix = "")
    {
        if (element.ValueKind != System.Text.Json.JsonValueKind.Object) return;

        foreach (var prop in element.EnumerateObject())
        {
            var path = string.IsNullOrEmpty(prefix) ? prop.Name : $"{prefix}.{prop.Name}";

            if (prop.Value.ValueKind == System.Text.Json.JsonValueKind.Object)
            {
                ApplyVmFromJsonElement(prop.Value, path);
            }
            else
            {
                ApplyVmProperty(path, prop.Value);
            }
        }
    }

    private void ApplyVmProperty(string path, System.Text.Json.JsonElement value)
    {
        // No bindings defined
        _ = path; _ = value;
    }

    // Component accessors
    public VBoxContainer Swarmhud => _swarmhud;
    public HBoxContainer Topbarslot => _topbarslot;
    public HBoxContainer Middlerow => _middlerow;
    public VBoxContainer Leftcolumn => _leftcolumn;
    public HBoxContainer Spawncontrolsslot => _spawncontrolsslot;
    public VBoxContainer Centerarea => _centerarea;
    public HBoxContainer Centerheader => _centerheader;
    public Label Genuitabbtn => _genuitabbtn;
    public Control Tabspacer => _tabspacer;
    public Label Taskgraphtabbtn => _taskgraphtabbtn;
    public VBoxContainer Centerbody => _centerbody;
    public VBoxContainer Genuihost => _genuihost;
    public VBoxContainer Rightcolumn => _rightcolumn;
    public VBoxContainer Agentpanelslot => _agentpanelslot;
    public VBoxContainer Consolepanelslot => _consolepanelslot;
}
