// <auto-generated>
// Generated by BoomHud.Gen.Godot from Swarmtopbar
// </auto-generated>

#nullable enable

using Godot;
using System;
using System.ComponentModel;

namespace GiantIsopod.Hosts.CompleteApp;

public partial class SwarmtopbarView : HBoxContainer
{
    public const string BoomHudSourceId = "sha256:208bf779ead92d81d1f4462382eb7df7b96338d8be9ca0619c1f5bb7602d9719";
    public const string BoomHudContractId = "";
    public static readonly string[] BoomHudNormalizedPseudoNodes = new string[0];

    private ISwarmtopbarViewModel? _viewModel;

    // Control references
    private HBoxContainer _swarmtopbar = null!;
    private Label _agentcount = null!;
    private Control _spacer = null!;
    private Label _runtimecount = null!;
    private Label _versionlabel = null!;

    public override void _Ready()
    {
        base._Ready();
        BindUiFromScene();
        InitializeUiFromScene();
    }

    private void BindUiFromScene()
    {
        _swarmtopbar = this;
        _agentcount = GetNode<Label>("agentcount");
        _spacer = GetNode<Control>("spacer");
        _runtimecount = GetNode<Label>("runtimecount");
        _versionlabel = GetNode<Label>("versionlabel");
    }

    private void InitializeUiFromScene()
    {
        {
        if ((object)this is Control c)
        {
            c.CustomMinimumSize = new Vector2(1920, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 32);
        }
        }
        this.AddThemeConstantOverride("separation", 12);
        this.AddThemeConstantOverride("h_separation", 12);
        this.AddThemeConstantOverride("v_separation", 12);
        this.AddThemeConstantOverride("margin_left", 12);
        this.AddThemeConstantOverride("margin_top", 6);
        this.AddThemeConstantOverride("margin_right", 12);
        this.AddThemeConstantOverride("margin_bottom", 6);

        _agentcount.AddThemeColorOverride("font_color", new Color(0.84705883f, 0.84705883f, 0.8980392f, 1f));
        _agentcount.Set("text", "Agents: 0");


        _runtimecount.AddThemeColorOverride("font_color", new Color(0.6f, 0.6f, 0.64705884f, 1f));
        _runtimecount.Set("text", "Runtimes: 0");

        _versionlabel.AddThemeColorOverride("font_color", new Color(0.44705883f, 0.44705883f, 0.49803922f, 1f));
        _versionlabel.Set("text", "v0.0.0");
    }

    private void BuildUi()
    {
        {
        if ((object)this is Control c)
        {
            c.CustomMinimumSize = new Vector2(1920, c.CustomMinimumSize.Y);
            c.CustomMinimumSize = new Vector2(c.CustomMinimumSize.X, 32);
        }
        }
        this.AddThemeConstantOverride("separation", 12);
        this.AddThemeConstantOverride("h_separation", 12);
        this.AddThemeConstantOverride("v_separation", 12);
        this.AddThemeConstantOverride("margin_left", 12);
        this.AddThemeConstantOverride("margin_top", 6);
        this.AddThemeConstantOverride("margin_right", 12);
        this.AddThemeConstantOverride("margin_bottom", 6);

        _agentcount = new Label();
        _agentcount.Name = "agentcount";
        _agentcount.AddThemeColorOverride("font_color", new Color(0.84705883f, 0.84705883f, 0.8980392f, 1f));
        _agentcount.Set("text", "Agents: 0");
        this.AddChild(_agentcount);

        _spacer = new Control();
        _spacer.Name = "spacer";
        this.AddChild(_spacer);

        _runtimecount = new Label();
        _runtimecount.Name = "runtimecount";
        _runtimecount.AddThemeColorOverride("font_color", new Color(0.6f, 0.6f, 0.64705884f, 1f));
        _runtimecount.Set("text", "Runtimes: 0");
        this.AddChild(_runtimecount);

        _versionlabel = new Label();
        _versionlabel.Name = "versionlabel";
        _versionlabel.AddThemeColorOverride("font_color", new Color(0.44705883f, 0.44705883f, 0.49803922f, 1f));
        _versionlabel.Set("text", "v0.0.0");
        this.AddChild(_versionlabel);
    }

    public void SetViewModel(ISwarmtopbarViewModel? viewModel)
    {
        if (_viewModel != null)
        {
            _viewModel.PropertyChanged -= OnViewModelPropertyChanged;
        }

        _viewModel = viewModel;

        if (_viewModel != null)
        {
            _viewModel.PropertyChanged += OnViewModelPropertyChanged;
            UpdateAllBindings();
        }
    }

    private void OnViewModelPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (_viewModel == null) return;

    }

    private void UpdateAllBindings()
    {
        if (_viewModel == null) return;

    }

    /// <summary>
    /// Apply VM state from JSON for snapshot rendering.
    /// This allows setting UI state without a full ViewModel implementation.
    /// </summary>
    public void ApplyVmJson(string json)
    {
        if (string.IsNullOrEmpty(json)) return;

        try
        {
            var doc = System.Text.Json.JsonDocument.Parse(json);
            ApplyVmFromJsonElement(doc.RootElement);
        }
        catch (System.Text.Json.JsonException ex)
        {
            GD.PrintErr($"ApplyVmJson failed to parse JSON: {ex.Message}");
        }
    }

    private void ApplyVmFromJsonElement(System.Text.Json.JsonElement element, string prefix = "")
    {
        if (element.ValueKind != System.Text.Json.JsonValueKind.Object) return;

        foreach (var prop in element.EnumerateObject())
        {
            var path = string.IsNullOrEmpty(prefix) ? prop.Name : $"{prefix}.{prop.Name}";

            if (prop.Value.ValueKind == System.Text.Json.JsonValueKind.Object)
            {
                ApplyVmFromJsonElement(prop.Value, path);
            }
            else
            {
                ApplyVmProperty(path, prop.Value);
            }
        }
    }

    private void ApplyVmProperty(string path, System.Text.Json.JsonElement value)
    {
        // No bindings defined
        _ = path; _ = value;
    }

    // Component accessors
    public HBoxContainer Swarmtopbar => _swarmtopbar;
    public Label Agentcount => _agentcount;
    public Control Spacer => _spacer;
    public Label Runtimecount => _runtimecount;
    public Label Versionlabel => _versionlabel;
}
