using GiantIsopod.Contracts.Core;
using GiantIsopod.Contracts.Protocol.Aieos;
using GiantIsopod.Contracts.Skills;
using Riok.Mapperly.Abstractions;

namespace GiantIsopod.Plugin.Mapping;

/// <summary>
/// Maps AIEOS wire types to domain models. Source-generated by Mapperly.
/// </summary>
[Mapper]
public partial class AieosMapper
{
    public AgentVisualInfo MapToVisualInfo(AieosEntity entity)
    {
        return new AgentVisualInfo(
            AgentId: entity.Metadata?.EntityId ?? "unknown",
            DisplayName: entity.Identity?.Names?.Nickname
                         ?? entity.Identity?.Names?.First
                         ?? entity.Metadata?.Alias
                         ?? "Agent",
            SkinTone: entity.Physicality?.Face?.Skin?.Tone,
            HairStyle: entity.Physicality?.Face?.Hair?.Style,
            HairColor: entity.Physicality?.Face?.Hair?.Color,
            AestheticArchetype: entity.Physicality?.Style?.AestheticArchetype
        );
    }

    public IReadOnlySet<string> MapToCapabilities(AieosCapabilities? capabilities)
    {
        if (capabilities?.Skills == null) return new HashSet<string>();
        return capabilities.Skills
            .Where(s => s.Name != null)
            .Select(s => s.Name!)
            .ToHashSet();
    }
}
