using GiantIsopod.Contracts.Core;
using GiantIsopod.Contracts.Protocol.Aieos;
using GiantIsopod.Contracts.Protocol.PiRpc;
using Riok.Mapperly.Abstractions;

namespace GiantIsopod.Plugin.Mapping;

/// <summary>
/// Maps protocol types to domain types. Source-generated by Mapperly.
/// </summary>
[Mapper]
public partial class ProtocolMapper
{
    public AgentActivityState MapToolEventToState(RpcToolEvent toolEvent)
    {
        return toolEvent.ToolName?.ToLowerInvariant() switch
        {
            "write" or "edit" or "bash" => AgentActivityState.Typing,
            "read" or "grep" or "find" or "ls" => AgentActivityState.Reading,
            _ => toolEvent.Status switch
            {
                "thinking" => AgentActivityState.Thinking,
                "waiting" => AgentActivityState.Waiting,
                _ => AgentActivityState.Idle
            }
        };
    }

    /// <summary>
    /// Maps an AIEOS entity to AgentVisualInfo for viewport rendering.
    /// </summary>
    public AgentVisualInfo MapAieosToVisualInfo(string agentId, AieosEntity entity)
    {
        var displayName = entity.Identity?.Names?.First
            ?? entity.Metadata?.Alias
            ?? agentId;

        return new AgentVisualInfo(
            agentId,
            displayName,
            SkinTone: entity.Physicality?.Face?.Skin?.Tone,
            HairStyle: entity.Physicality?.Face?.Hair?.Style,
            HairColor: entity.Physicality?.Face?.Hair?.Color,
            AestheticArchetype: entity.Physicality?.Style?.AestheticArchetype);
    }

    /// <summary>
    /// Extracts capability skill names from an AIEOS entity.
    /// </summary>
    public HashSet<string> MapAieosToCapabilities(AieosEntity entity)
    {
        if (entity.Capabilities?.Skills == null)
            return new HashSet<string>();

        return entity.Capabilities.Skills
            .Where(s => s.Name != null)
            .Select(s => s.Name!)
            .ToHashSet();
    }
}
