using GiantIsopod.Contracts.Core;
using GiantIsopod.Contracts.Protocol.PiRpc;
using Riok.Mapperly.Abstractions;

namespace GiantIsopod.Plugin.Mapping;

/// <summary>
/// Maps Pi RPC events to domain activity states. Source-generated by Mapperly.
/// </summary>
[Mapper]
public partial class ProtocolMapper
{
    public AgentActivityState MapToolEventToState(RpcToolEvent toolEvent)
    {
        return toolEvent.ToolName?.ToLowerInvariant() switch
        {
            "write" or "edit" or "bash" => AgentActivityState.Typing,
            "read" or "grep" or "find" or "ls" => AgentActivityState.Reading,
            _ => toolEvent.Status switch
            {
                "thinking" => AgentActivityState.Thinking,
                "waiting" => AgentActivityState.Waiting,
                _ => AgentActivityState.Idle
            }
        };
    }
}
